info:
  title: test
  version: 1.1.1
  x-lastModified: Jun 06, 2017 00:21AM PST
paths:
  /test:
    get:
      parameters: []
      produces:
      - application/json
      responses:
        "200":
          description: Success response##%%**@''
    patch:
      parameters: []
      produces:
      - application/json
      responses:
        "200":
          description: Success response
    post:
      parameters: []
      produces:
      - application/json
      responses:
        "200":
          description: Success response
    put:
      parameters: []
      produces:
      - application/json
      responses:
        "200":
          description: Success response
swagger: "2.0"
