definitions:
  GiveNewSchemaNameHere:
    properties:
      message:
        default: Hello World!
        type: string
    type: object
info:
  description: aaa
  title: patch11
  version: 1.0.0
  x-lastModified: May 11, 2017 03:15AM PST
paths:
  /pet:
    delete:
      parameters: []
      produces:
      - application/json
      responses:
        "200":
          description: Success response
    get:
      parameters: []
      produces:
      - application/json
      responses:
        "200":
          description: Success response
    patch:
      parameters: []
      produces:
      - application/json
      responses:
        "200":
          description: Success response
          examples:
            application/json:
              message: Hello World!
          schema:
            $ref: '#/definitions/GiveNewSchemaNameHere'
    post:
      parameters: []
      produces:
      - application/json
      responses:
        "200":
          description: Success response
    put:
      parameters: []
      produces:
      - application/json
      responses:
        "200":
          description: Success response
swagger: "2.0"
